apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to Nginx!</title>
      </head>
      <body>
        <h1>Success! The Nginx server is running in your Kubernetes cluster!</h1>
      </body>
    </html>
